"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useEffect, useState } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <QueryClientProvider client={queryClient}>
        <body>{children}</body>
      </QueryClientProvider>
      <footer className="m-3 flex justify-center">
        ssourabh025@gmail.com ❖ +91 9516550023 ❖ Bangalore,KA ❖{" "}
        <a href="https://sourabh-portfolio-coral.vercel.app/">Portfolio</a> ❖{" "}
        <a href="https://www.linkedin.com/in/sourabh58">LinkedIn</a>
      </footer>
    </html>
  );
}
